# gitpod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Environment & Install Dependencies
    init: |
      echo "Environment setup complete!"
  - name: "AWS profiles"
    init: |
      mkdir -p ~/.aws
      cp aws_profiles ~/.aws/config
  - name: "bashrc"
    init: |
      cp bashrc ~/.bashrc
      source ~/.bashrc
  - name: "vnc startup"
    init: |
      mkdir -p ~/.vnc
      cp vnc_xstartup ~/.vnc/xstartup
      chmod +x ~/.vnc/xstartup


ports:
  - port: 3000
    description: The main application web server
    onOpen: open-preview
  - port: 5900
    description: VNC Server
    onOpen: ignore
  - port: 5901
    onOpen: ignore
  - port: 6080
    description: VNC Viewer
    onOpen: ignore

# vscode:
#   extensions:
#     - hashicorp.terraform
#     - ms-azuretools.vscode-docker
#     - redhat.vscode-yaml
#     - ms-kubernetes-tools.vscode-kubernetes-tools
#     - amazonwebservices.aws-toolkit-vscode
#     - eamodio.gitlens
