---
# .gitpod.yml
image:
  file: .gitpod.Dockerfile.Rocky

tasks:
  - name: Env Setup
    init: bash setup_tools.sh
    command: echo "Environment ready!"

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - eamodio.gitlens

ports:
  - port: 8080
    onOpen: open-preview

