# gitpod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install tools
    init: ./setup_tools.sh
    command: echo "Environment ready"

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - amazonwebservices.aws-toolkit-vscode
    - eamodio.gitlens
