[tools]
# vim = "latest"
argocd = "latest"
awscli = "latest"
eksctl = "latest"
fzf = "latest"
go = "1.24.5"
istioctl = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
loki-logcli = "latest"
node = "22.17.1"
python = "3.12"
terraform = "1.12.2"
terragrunt = "latest"
tfswitch = "latest"
uv = "latest"
yq = "latest"
